services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./admin/dist:/usr/share/nginx/html/admin:ro
      - ./miniapp/dist:/usr/share/nginx/html/wap:ro

  backend:
    image: node:latest
    restart: always
    environment:
      - MYSQL_PORT=3306
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=00000000
      - MYSQL_DATABASE=duty_free_shopping
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=00000000
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm start

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=00000000
      - MYSQL_DATABASE=duty_free_shopping
      - MYSQL_USER=root
      - MYSQL_PASSWORD=00000000
      - TZ=Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-time-zone='+08:00'

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    environment:
      - REDIS_PASSWORD=00000000
    volumes:
      - redis_data:/data
    command: redis-server --requirepass 00000000

volumes:
  mysql_data:
  redis_data:
